(ns musicaltec-app.stock.subs
  (:require [re-frame.core :as rf]))

(rf/reg-sub :stock                      (fn [db _] (:stock db)))
(rf/reg-sub :stock/tab                  (fn [db _] (get-in db [:stock :tab])))
(rf/reg-sub :stock/items                (fn [db _] (get-in db [:stock :items])))
(rf/reg-sub :stock/query                (fn [db _] (get-in db [:stock :query])))
(rf/reg-sub :stock/page                 (fn [db _] (get-in db [:stock :page])))
(rf/reg-sub :stock/total-pages          (fn [db _] (get-in db [:stock :total-pages])))
(rf/reg-sub :stock/total                (fn [db _] (get-in db [:stock :total])))
(rf/reg-sub :stock/per-page             (fn [db _] (get-in db [:stock :per-page])))
(rf/reg-sub :stock/loading?             (fn [db _] (get-in db [:stock :loading?])))
(rf/reg-sub :stock/error                (fn [db _] (get-in db [:stock :error])))
(rf/reg-sub :stock/counterparty-results (fn [db _] (get-in db [:stock :counterparty-results])))
(rf/reg-sub :stock/item-drawer          (fn [db _] (get-in db [:stock :item-drawer])))
(rf/reg-sub :stock/item-drawer-form     (fn [db _] (get-in db [:stock :item-drawer :form])))
(rf/reg-sub :stock/item-drawer-saving?  (fn [db _] (get-in db [:stock :item-drawer :saving?])))
(rf/reg-sub :stock/movement-drawer      (fn [db _] (get-in db [:stock :movement-drawer])))
(rf/reg-sub :stock/movement-form        (fn [db _] (get-in db [:stock :movement-drawer :form])))
(rf/reg-sub :stock/movement-saving?     (fn [db _] (get-in db [:stock :movement-drawer :saving?])))
